const ERROR_CODE_RESOURCE_NOT_FOUND = 404;
const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_INTERNAL_SERVER_ERROR = 500;

export {
  ERROR_CODE_RESOURCE_NOT_FOUND,
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_INTERNAL_SERVER_ERROR,
};
